spring:
  redis:
    cluster:
      nodes:
        - 192.168.44.129:7001
        - 192.168.44.129:7002
        - 192.168.44.129:7003
        - 192.168.44.129:7004
        - 192.168.44.129:7005
        - 192.168.44.129:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接

  application:
    name: usian-item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: aaaa
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 192.168.44.128
    username: yyy
    password: 1111
    virtual-host: /usian



server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
mybatis:
  # 定义mapper.xml的路径
  mapper-locations: classpath*:mapper/*.xml
  #起别名。可省略写mybatis的xml中的resultType的全路径
  type-aliases-package: com.usian.pojo
# tkmapper配置
mapper:
  not-empty: false
  identity: mysql #指定tkmapper加载的数据库